-- physical screen dimensions / 0.5625, 16x9
WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 720
-- virtual resolution dimensions
VIRTUAL_WIDTH = 416
VIRTUAL_HEIGHT = 234

-- tile size
TILE_SIZE = 16
-- camera
LEFT_CAMERA_EDGE = 0.5 * VIRTUAL_WIDTH - 4 * TILE_SIZE
RIGHT_CAMERA_EDGE = 0.5 * VIRTUAL_WIDTH + 3 * TILE_SIZE

-- direction
DIRECTION_LEFT = 1
DIRECTION_RIGHT = 0

-- characters
PLAYER_CLIMB_SPEED = 35
PLAYER_FALL_SPEED = 6
PLAYER_JUMP_VELOCITY = 190
PLAYER_WALK_SPEED = 70
SNAIL_SLIDE_SPEED = 100
SNAIL_WALK_SPEED = 15

-- tile ids
TILE_ID_EMPTY = 0
TILE_ID_WATER = 1
TILE_ID_GROUND = 5

-- debug mode
DEBUG=0